"""empty message

Revision ID: 90a23202028e
Revises: 
Create Date: 2020-01-18 13:45:13.548902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a23202028e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('base', sa.String(length=200), nullable=True))
    op.add_column('forecast', sa.Column('clouds_all', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('cod', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('dt', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('main_feels_like', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('main_grnd_level', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('main_humidity', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('main_pressure', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('main_sea_level', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('main_temp', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('main_temp_max', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('main_temp_min', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('forecast', sa.Column('rain_1h', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('rain_3h', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('snow_1h', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('snow_3h', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('sys_country', sa.String(length=200), nullable=True))
    op.add_column('forecast', sa.Column('sys_id', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('sys_message', sa.String(length=200), nullable=True))
    op.add_column('forecast', sa.Column('sys_sunrise', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('sys_sunset', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('sys_type', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('timezone', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('visibility', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('weather_description', sa.String(length=200), nullable=True))
    op.add_column('forecast', sa.Column('weather_icon', sa.String(length=200), nullable=True))
    op.add_column('forecast', sa.Column('weather_id', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('weather_main', sa.String(length=200), nullable=True))
    op.add_column('forecast', sa.Column('wind_deg', sa.Integer(), nullable=True))
    op.add_column('forecast', sa.Column('wind_speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'wind_speed')
    op.drop_column('forecast', 'wind_deg')
    op.drop_column('forecast', 'weather_main')
    op.drop_column('forecast', 'weather_id')
    op.drop_column('forecast', 'weather_icon')
    op.drop_column('forecast', 'weather_description')
    op.drop_column('forecast', 'visibility')
    op.drop_column('forecast', 'timezone')
    op.drop_column('forecast', 'sys_type')
    op.drop_column('forecast', 'sys_sunset')
    op.drop_column('forecast', 'sys_sunrise')
    op.drop_column('forecast', 'sys_message')
    op.drop_column('forecast', 'sys_id')
    op.drop_column('forecast', 'sys_country')
    op.drop_column('forecast', 'snow_3h')
    op.drop_column('forecast', 'snow_1h')
    op.drop_column('forecast', 'rain_3h')
    op.drop_column('forecast', 'rain_1h')
    op.drop_column('forecast', 'name')
    op.drop_column('forecast', 'main_temp_min')
    op.drop_column('forecast', 'main_temp_max')
    op.drop_column('forecast', 'main_temp')
    op.drop_column('forecast', 'main_sea_level')
    op.drop_column('forecast', 'main_pressure')
    op.drop_column('forecast', 'main_humidity')
    op.drop_column('forecast', 'main_grnd_level')
    op.drop_column('forecast', 'main_feels_like')
    op.drop_column('forecast', 'dt')
    op.drop_column('forecast', 'cod')
    op.drop_column('forecast', 'clouds_all')
    op.drop_column('forecast', 'base')
    # ### end Alembic commands ###
